In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import plotly.express as px

In [2]:
filename = 'swiggy_vs_zomato_3000.csv'
df = pd.read_csv(filename)
df.head(1)

,restaurant_id,restaurant_name,city,locality,restaurant_type,cuisines,distance_from_city_center_km,opening_time,closing_time,days_operational,...,swiggy_market_share_pct,zomato_market_share_pct,platform_performance_better,amenities,amenities_count,has_own_website,has_own_app,food_license_verified,listing_date,days_listed
0,REST000001,Restaurant_1,Mumbai,Mumbai_Locality_9,Cafe,Italian,4.1,12:00,22:00,601,...,50.0,50.0,Swiggy Better,Live Music; Family Friendly; Vegan Options; Wi...,6,False,False,True,2023-03-04,1168

In [3]:
df.isnull()

,restaurant_id,restaurant_name,city,locality,restaurant_type,cuisines,distance_from_city_center_km,opening_time,closing_time,days_operational,...,swiggy_market_share_pct,zomato_market_share_pct,platform_performance_better,amenities,amenities_count,has_own_website,has_own_app,food_license_verified,listing_date,days_listed
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2495,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2496,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2497,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2498,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2499,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [4]:
df.columns

Index(['restaurant_id', 'restaurant_name', 'city', 'locality',
       'restaurant_type', 'cuisines', 'distance_from_city_center_km',
       'opening_time', 'closing_time', 'days_operational', 'swiggy_rating',
       'swiggy_total_reviews', 'zomato_rating', 'zomato_total_reviews',
       'average_rating_both_platforms', 'avg_cost_per_person_inr',
       'price_category', 'swiggy_delivery_fee_inr', 'zomato_delivery_fee_inr',
       'swiggy_avg_delivery_time_minutes', 'zomato_avg_delivery_time_minutes',
       'swiggy_platform_commission_pct', 'zomato_platform_commission_pct',
       'swiggy_discount_frequency_pct', 'zomato_discount_frequency_pct',
       'swiggy_estimated_monthly_orders', 'zomato_estimated_monthly_orders',
       'swiggy_estimated_monthly_revenue_inr',
       'zomato_estimated_monthly_revenue_inr',
       'swiggy_estimated_net_profit_inr', 'zomato_estimated_net_profit_inr',
       'swiggy_market_share_pct', 'zomato_market_share_pct',
       'platform_performance_better', 'amenities', 'amenities_count',
       'has_own_website', 'has_own_app', 'food_license_verified',
       'listing_date', 'days_listed'],
      dtype='object')

In [5]:
df.describe()

,distance_from_city_center_km,days_operational,swiggy_rating,swiggy_total_reviews,zomato_rating,zomato_total_reviews,average_rating_both_platforms,avg_cost_per_person_inr,swiggy_delivery_fee_inr,zomato_delivery_fee_inr,...,swiggy_estimated_monthly_orders,zomato_estimated_monthly_orders,swiggy_estimated_monthly_revenue_inr,zomato_estimated_monthly_revenue_inr,swiggy_estimated_net_profit_inr,zomato_estimated_net_profit_inr,swiggy_market_share_pct,zomato_market_share_pct,amenities_count,days_listed
count,2500.00000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,...,2500.00000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000
mean,7.53788,1844.268400,3.985640,2467.222800,4.006000,2559.023600,3.995820,823.042400,57.877600,57.877600,...,199.29360,200.322400,129806.193600,130244.388400,124030.646800,124435.133200,54.065200,45.934800,5.471200,1822.907200
std,4.23873,1044.579864,0.400917,1414.963408,0.398351,1442.346122,0.288078,392.548909,20.552109,20.552109,...,67.42941,67.859458,76221.487739,76046.870279,75205.863176,75025.670113,7.859266,7.859266,1.700096,1039.655203
min,0.50000,33.000000,2.500000,10.000000,2.500000,10.000000,2.900000,150.000000,30.000000,30.000000,...,76.00000,80.000000,12305.000000,12136.000000,10545.000000,9496.000000,40.000000,25.000000,3.000000,31.000000
25%,3.80000,946.250000,3.700000,1225.750000,3.700000,1311.750000,3.800000,475.000000,39.000000,39.000000,...,146.00000,147.000000,68975.250000,70243.000000,64221.500000,64905.000000,48.000000,40.000000,4.000000,925.500000
50%,7.40000,1846.000000,4.000000,2460.000000,4.000000,2604.000000,4.000000,834.500000,57.000000,57.000000,...,190.00000,192.000000,117664.500000,120332.000000,112337.000000,114506.500000,53.000000,47.000000,5.000000,1806.000000
75%,11.20000,2728.250000,4.300000,3672.750000,4.300000,3791.000000,4.200000,1160.250000,76.000000,76.000000,...,246.00000,245.000000,176867.000000,176962.000000,171062.500000,171530.250000,60.000000,52.000000,7.000000,2711.500000
max,15.00000,3649.000000,5.000000,5000.000000,5.000000,5000.000000,4.900000,1500.000000,95.000000,95.000000,...,428.00000,420.000000,413475.000000,464880.000000,406537.000000,457480.000000,75.000000,60.000000,8.000000,3647.000000

In [6]:
fig = px.scatter(x=df['swiggy_rating'], y=df['zomato_rating'])
fig.show()

In [7]:
avg_cost = df.groupby('restaurant_type')['avg_cost_per_person_inr'].mean().reset_index()
fig = px.bar(
    avg_cost,
    x='restaurant_type',
    y='avg_cost_per_person_inr'
)
fig.show()

In [8]:
summary = (
    df.groupby('restaurant_type')
    .agg({
        'avg_cost_per_person_inr':'mean',
        'swiggy_rating':'mean',
        'zomato_rating':'mean'
    })
    .reset_index()
)

long_df = pd.DataFrame({
    'restaurant_type': summary['restaurant_type'].tolist()*2,
    'avg_cost_per_person_inr': list(summary['avg_cost_per_person_inr']) * 2,
    'rating': list(summary['swiggy_rating']) + list(summary['zomato_rating']),
    'platform': ['Swiggy'] * len(summary) + ['Zomato'] * len(summary)
})
fig = px.bar(
    long_df,
    x='restaurant_type',
    y='avg_cost_per_person_inr',
    facet_row='platform',
    color='rating',
    color_continuous_scale='Viridis',
    range_color=[1, 5],
    title='Average Cost Per Person by Restaurant Type'
)
fig.show()

In [9]:
df['cuisines'].value_counts().index

Index(['Biryani', 'Street Food', 'Mediterranean', 'Bakery', 'Korean',
       'Seafood', 'Mexican', 'Cafe', 'Italian', 'South Indian',
       ...
       'North Indian; Thai', 'Cafe; Multi-Cuisine', 'North Indian; Korean',
       'Seafood; Mediterranean', 'Vietnamese; Bakery', 'Italian; South Indian',
       'Mughlai; South Indian', 'Pan-Asian; Vietnamese', 'Italian; Korean',
       'Continental; Seafood'],
      dtype='object', name='cuisines', length=445)

In [10]:
cuisines = df['cuisines'].value_counts()
cuisines_list = cuisines.index
cuisines_counts = cuisines.values



for i,j in zip(cuisines_list,cuisines_counts):
    if j > 7:
        print(f"{i}: {j}")
    else:
        continue

Biryani: 84
Street Food: 80
Mediterranean: 80
Bakery: 79
Korean: 79
Seafood: 70
Mexican: 69
Cafe: 67
Italian: 65
South Indian: 65
Continental: 65
North Indian: 64
Multi-Cuisine: 64
Mughlai: 63
Lebanese: 63
Desserts: 63
Chinese: 61
Fast Food: 60
Pan-Asian: 59
Japanese: 59
Thai: 58
Vietnamese: 47

In [11]:
valid_cuisines = cuisines[cuisines>7].index
cuisine_df = df[df['cuisines'].isin(valid_cuisines)]

In [12]:
avg_cost_cuisine = cuisine_df.groupby('cuisines')['avg_cost_per_person_inr'].median().reset_index()
avg_cost_cuisine

         cuisines  avg_cost_per_person_inr
0          Bakery                    824.0
1         Biryani                    810.0
2            Cafe                    809.0
3         Chinese                    948.0
4     Continental                    860.0
5        Desserts                    871.0
6       Fast Food                    848.5
7         Italian                    942.0
8        Japanese                    869.0
9          Korean                    919.0
10       Lebanese                    909.0
11  Mediterranean                    879.0
12        Mexican                    859.0
13        Mughlai                    908.0
14  Multi-Cuisine                    840.5
15   North Indian                    882.5
16      Pan-Asian                    878.0
17        Seafood                    832.0
18   South Indian                    859.0
19    Street Food                    705.5
20           Thai                    863.5
21     Vietnamese                    748.0

In [13]:
fig = px.bar(
    avg_cost_cuisine,
    y='cuisines',
    x='avg_cost_per_person_inr',
    orientation='h'
)
fig.show()

In [14]:
city_cost = df.groupby('city')['avg_cost_per_person_inr'].median().reset_index()
city_cost

        city  avg_cost_per_person_inr
0  Ahmedabad                    864.0
1  Bangalore                    844.5
2    Chennai                    785.5
3      Delhi                    860.5
4  Hyderabad                    797.0
5     Jaipur                    805.5
6    Kolkata                    776.0
7    Lucknow                    795.0
8     Mumbai                    874.5
9       Pune                    863.5

In [15]:
fig_1 = px.bar(
    city_cost,
    x='avg_cost_per_person_inr',
    y='city',
    orientation='h',
    color_discrete_sequence=['green']
)
fig_1.show()

In [16]:
ratings_df = pd.melt(
    cuisine_df,
    id_vars='cuisines',
    value_vars=['swiggy_rating', 'zomato_rating'],
    var_name='platform',
    value_name='ratings'
)

ratings_df['platform'] = ratings_df['platform'].replace({
    'swiggy_rating': 'Swiggy',
    'zomato_rating': 'Zomato'
})

In [17]:
ratings_df.head()

        cuisines platform  ratings
0        Italian   Swiggy      3.6
1        Mughlai   Swiggy      4.2
2  Mediterranean   Swiggy      3.8
3       Desserts   Swiggy      3.3
4        Mexican   Swiggy      4.8

In [18]:
ratings_df_new = ratings_df.groupby(['cuisines','platform'])['ratings'].mean().reset_index()
ratings_df_new

         cuisines platform   ratings
0          Bakery   Swiggy  4.051899
1          Bakery   Zomato  3.996203
2         Biryani   Swiggy  4.036905
3         Biryani   Zomato  4.003571
4            Cafe   Swiggy  4.025373
5            Cafe   Zomato  4.005970
6         Chinese   Swiggy  4.034426
7         Chinese   Zomato  4.040984
8     Continental   Swiggy  4.015385
9     Continental   Zomato  4.021538
10       Desserts   Swiggy  4.001587
11       Desserts   Zomato  3.988889
12      Fast Food   Swiggy  4.065000
13      Fast Food   Zomato  4.026667
14        Italian   Swiggy  3.910769
15        Italian   Zomato  4.049231
16       Japanese   Swiggy  3.966102
17       Japanese   Zomato  3.993220
18         Korean   Swiggy  3.977215
19         Korean   Zomato  3.991139
20       Lebanese   Swiggy  4.087302
21       Lebanese   Zomato  4.014286
22  Mediterranean   Swiggy  3.992500
23  Mediterranean   Zomato  3.983750
24        Mexican   Swiggy  3.940580
25        Mexican   Zomato  4.017391
26        Mughlai   Swiggy  3.880952
27        Mughlai   Zomato  3.987302
28  Multi-Cuisine   Swiggy  3.923437
29  Multi-Cuisine   Zomato  3.987500
30   North Indian   Swiggy  3.975000
31   North Indian   Zomato  4.087500
32      Pan-Asian   Swiggy  4.025424
33      Pan-Asian   Zomato  4.044068
34        Seafood   Swiggy  3.912857
35        Seafood   Zomato  3.944286
36   South Indian   Swiggy  3.915385
37   South Indian   Zomato  4.023077
38    Street Food   Swiggy  3.956250
39    Street Food   Zomato  4.026250
40           Thai   Swiggy  3.898276
41           Thai   Zomato  3.989655
42     Vietnamese   Swiggy  3.931915
43     Vietnamese   Zomato  3.976596

In [19]:
ratings_df_new.groupby('platform')['ratings'].mean().reset_index()

  platform   ratings
0   Swiggy  3.978388
1   Zomato  4.009049

In [20]:
fig = px.bar(
    ratings_df_new,
    x='cuisines',
    y='ratings',
    color='platform',
    barmode='group'
)
fig.show()

In [21]:
df.columns

Index(['restaurant_id', 'restaurant_name', 'city', 'locality',
       'restaurant_type', 'cuisines', 'distance_from_city_center_km',
       'opening_time', 'closing_time', 'days_operational', 'swiggy_rating',
       'swiggy_total_reviews', 'zomato_rating', 'zomato_total_reviews',
       'average_rating_both_platforms', 'avg_cost_per_person_inr',
       'price_category', 'swiggy_delivery_fee_inr', 'zomato_delivery_fee_inr',
       'swiggy_avg_delivery_time_minutes', 'zomato_avg_delivery_time_minutes',
       'swiggy_platform_commission_pct', 'zomato_platform_commission_pct',
       'swiggy_discount_frequency_pct', 'zomato_discount_frequency_pct',
       'swiggy_estimated_monthly_orders', 'zomato_estimated_monthly_orders',
       'swiggy_estimated_monthly_revenue_inr',
       'zomato_estimated_monthly_revenue_inr',
       'swiggy_estimated_net_profit_inr', 'zomato_estimated_net_profit_inr',
       'swiggy_market_share_pct', 'zomato_market_share_pct',
       'platform_performance_better', 'amenities', 'amenities_count',
       'has_own_website', 'has_own_app', 'food_license_verified',
       'listing_date', 'days_listed'],
      dtype='object')

In [22]:
df['restaurant_type'].unique()

array(['Cafe', 'Casual Dining', 'Fine Dine', 'Cloud Kitchen',
       'Food Truck', 'QSR (Quick Service)'], dtype=object)

In [23]:
# monthly orders
monthly_orders_df = pd.melt(
    cuisine_df,
    id_vars='cuisines',
    value_vars=['swiggy_estimated_monthly_orders','zomato_estimated_monthly_orders'],
    var_name='platform',
    value_name='monthly_orders'
)
monthly_orders_df['platform'] = monthly_orders_df['platform'].replace({
    'swiggy_estimated_monthly_orders': 'swiggy',
    'zomato_estimated_monthly_orders': 'zomato'
})

In [24]:
monthly_orders_df['cuisines'].unique()

array(['Italian', 'Mughlai', 'Mediterranean', 'Desserts', 'Mexican',
       'Thai', 'Chinese', 'Cafe', 'Multi-Cuisine', 'Pan-Asian', 'Seafood',
       'Japanese', 'Continental', 'Lebanese', 'North Indian',
       'South Indian', 'Korean', 'Bakery', 'Street Food', 'Biryani',
       'Fast Food', 'Vietnamese'], dtype=object)

In [25]:
monthly_orders = monthly_orders_df.groupby(['cuisines','platform'])['monthly_orders'].median().reset_index()
monthly_orders.head()

  cuisines platform  monthly_orders
0   Bakery   swiggy           206.0
1   Bakery   zomato           211.0
2  Biryani   swiggy           186.0
3  Biryani   zomato           194.5
4     Cafe   swiggy           204.0

In [26]:
max_monthly_oders = monthly_orders.groupby('platform')['monthly_orders'].max().reset_index()

In [27]:
max_monthly_oders.values

array([['swiggy', 222.0],
       ['zomato', 223.0]], dtype=object)

In [28]:
max_monthly_oders_c = monthly_orders.groupby('cuisines')['monthly_orders'].max().reset_index()

In [29]:
max_monthly_oders_c.values

array([['Bakery', 211.0],
       ['Biryani', 194.5],
       ['Cafe', 208.0],
       ['Chinese', 215.0],
       ['Continental', 181.0],
       ['Desserts', 216.0],
       ['Fast Food', 219.5],
       ['Italian', 179.0],
       ['Japanese', 223.0],
       ['Korean', 170.0],
       ['Lebanese', 176.0],
       ['Mediterranean', 185.5],
       ['Mexican', 189.0],
       ['Mughlai', 181.0],
       ['Multi-Cuisine', 188.5],
       ['North Indian', 212.0],
       ['Pan-Asian', 183.0],
       ['Seafood', 199.0],
       ['South Indian', 198.0],
       ['Street Food', 206.0],
       ['Thai', 187.5],
       ['Vietnamese', 182.0]], dtype=object)

In [30]:
min_monthly_orders = monthly_orders.groupby('platform')['monthly_orders'].min().reset_index()
min_monthly_orders

  platform  monthly_orders
0   swiggy           169.0
1   zomato           170.0

In [31]:
min_monthly_oders_c = monthly_orders.groupby('cuisines')['monthly_orders'].min().reset_index()
min_monthly_oders_c

         cuisines  monthly_orders
0          Bakery           206.0
1         Biryani           186.0
2            Cafe           204.0
3         Chinese           213.0
4     Continental           175.0
5        Desserts           197.0
6       Fast Food           216.5
7         Italian           175.0
8        Japanese           222.0
9          Korean           169.0
10       Lebanese           171.0
11  Mediterranean           181.5
12        Mexican           188.0
13        Mughlai           181.0
14  Multi-Cuisine           184.5
15   North Indian           211.5
16      Pan-Asian           180.0
17        Seafood           187.0
18   South Indian           193.0
19    Street Food           200.5
20           Thai           182.5
21     Vietnamese           179.0

In [32]:
monthly_orders.groupby('platform')['monthly_orders'].median().reset_index()

  platform  monthly_orders
0   swiggy          186.50
1   zomato          190.75

In [33]:
monthly_orders_df = pd.melt(
    cuisine_df,
    id_vars=['cuisines','city'],
    value_vars=['swiggy_estimated_monthly_orders','zomato_estimated_monthly_orders'],
    var_name='platform',
    value_name='monthly_orders'
)
monthly_orders_df['platform'] = monthly_orders_df['platform'].replace({
    'swiggy_estimated_monthly_orders': 'swiggy',
    'zomato_estimated_monthly_orders': 'zomato'
})

In [34]:
monthly_orders_df.to_csv('monthly_orders.csv')

In [35]:
net_profit_df = pd.melt(
    cuisine_df,
    id_vars=['cuisines','city'],
    value_vars=['swiggy_estimated_net_profit_inr','zomato_estimated_net_profit_inr'],
    var_name='platform',
    value_name='net_profit'
)
net_profit_df['platform'] = net_profit_df['platform'].replace({
    'swiggy_estimated_net_profit_inr': 'swiggy',
    'zomato_estimated_net_profit_inr': 'zomato'
})

In [36]:
net_profit_df

           cuisines     city platform  net_profit
0           Italian   Mumbai   swiggy      109348
1           Mughlai   Mumbai   swiggy      197113
2     Mediterranean   Mumbai   swiggy      168510
3          Desserts   Mumbai   swiggy      109295
4           Mexican   Mumbai   swiggy      215098
...             ...      ...      ...         ...
2923    Continental  Lucknow   zomato      326951
2924   North Indian  Lucknow   zomato      104000
2925      Pan-Asian  Lucknow   zomato       80973
2926  Multi-Cuisine  Lucknow   zomato       77666
2927        Chinese  Lucknow   zomato      232406

[2928 rows x 4 columns]

In [37]:
net_profit_df.to_csv('net_profit.csv')

In [38]:
net_profit_df.groupby('platform')['net_profit'].sum().reset_index()

  platform  net_profit
0   swiggy   186706825
1   zomato   187489802